### PR TITLE
Support for Mobile User-Agents

### PR DESCRIPTION
**Pull request by hoffi**
Added support to choose a mobile user agent.

Contains following options: 
* Browser Default - Uses default user agent (Default option)
* iPhone
* iPad
* Android (Nexus One)

Screenshot

### CODE REVIEW

**Comment by hoffi** [comment]
#145

**Comment by johnotander** [comment]
Sorry for the delay in responding, if you wanted rebase this I'd love to merge it in, @hoffi. Otherwise I could do so as well. Thanks!

**Comment by hoffi** [comment]
No problem @johnotander. I have rebased it :)

**Comment by johnotander** [comment]
Thanks!

**Pull request merged**
